disabled_rules:
  - nesting
  - type_name
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation 
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - sorted_first_last
  - single_test_class
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - unavailable_function

# We should enable this
#- missing_docs

  # Questionable?
  #- explicit_enum_raw_value
  #- explicit_type_interface
  #- explicit_acl
  #- explicit_top_level_acl
  #- extension_access_modifier
  #- file_header
  #- implicitly_unwrapped_optional

# Probably not
  # We group things in extensions
  #- no_grouping_extension
  # Goes against the order in SwiftFormat
  #- modifier_order
  # Goes against other rule
  #- redundant_type_annotation
  # We use them sometimes
  #- trailing_closure

# enable in the future
# empty_count: warning

excluded:
  LaunchKit/Package.swift

trailing_comma:
  severity: warning
  mandatory_comma: true

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 40
    error: 1000
  excluded:
    - id
    - to
    - vc

type_name:
  excluded:
    - UI

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)

